### ISSUE TITLE
Strings!

### ISSUE THREAD

**Issue by neoadventist** [GoogleCloudPlatform/nodejs-docs-samples#122]
If I have 
```
obj = {
valueType: 'INT64',
          points: {
            interval: {
              startTime: now,
              endTime: now
            },
            value: {
             
            }
          }
}
```

then i set 

`obj.valueType = 'STRING';` and `obj.points.value.int64Value = 'some JSON'`

I get 

` message: 'Invalid value at \'time_series[0].points.value.int64_value\' (TYPE_INT64),` 

I want to be able to send JSON to stack driver when an exception occurs in the program. Currently i'm only able to send integers.

**Comment by jmdobry** [comment]
Can you give additional context as to what you're doing, or why you opened an issue on this particular repository? Are you having trouble running one of the samples in this repository? Otherwise, you can get support at https://gcp-slack.appspot.com/ or by posting a question on [Stack Overflow](http://stackoverflow.com/questions/tagged/stackdriver).

**Comment by neoadventist** [comment]
Was trying to send a JSON value instead of a number and received an error. didn't know about the gcp-slack. I'll try to see if someone has solved this problem there. Is there a form or place for stackdriver?

**Comment by jmdobry** [comment]
There's a #monitoring channel in Slack, and the Stack Overflow link I gave you links to the StackDriver tag on Stack Overflow.

**Comment by neoadventist** [comment]
joined it thanks @jmdobry

**Comment by neoadventist** [comment]
Turns out you can't send strings if anyone looks at this in the future.
