### ISSUE TITLE
Storage files missing for some tests

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#1435]
Hi, could you have a look, this is blocking us from merging PRs. The OCR and imagemagick tests are failing because `zombies.jpg` isn't in the storage bucket. Thanks

**Comment by ace-n** [comment]
This image keeps getting deleted for some reason, and I can't seem to figure out why. (Maybe the Node 6 sample tests? 🤔 These tests should only delete from the _nodejs-docs-samples-tests-**functions**_ bucket, not _nodejs-docs-samples-tests_.)

In the meantime, I've enabled a hold on it - if the deletion is caused by an automated process, this should (hopefully) cause said process to "halt and catch fire".

Failing that, we can set up [GCS access logging](https://cloud.google.com/storage/docs/access-logs#delivery) for this bucket. (I wasn't able to find anything in Stackdriver, unfortunately.)

**Comment by fhinkel** [comment]
The `ocr` test is still failing: 

```
Detected language "und" for wakeupcat.jpg
Looking for text in image wakeupcat.jpg
Extracted text from image:
Detected language "und" for wakeupcat.jpg
File wakeupcat.jpg processed.
```

Looks like we're not detecting the test on the image anymore. Not sure if the algorithm changed or if we're calling the API incorrectly.

**Comment by fhinkel** [comment]
Turns out the image is not in the storage bucket.

**Comment by ace-n** [comment]
Restored `wakeupcat.jpg`. Also enabled a hold, so any automated deletion attempt should fail.

**Comment by fhinkel** [comment]
Thank you, tests are passing 😄
