### ISSUE TITLE
scheduleinstance error 

### ISSUE THREAD

**Issue by harryliu123** [GoogleCloudPlatform/nodejs-docs-samples#1451]
git clone https://github.com/GoogleCloudPlatform/nodejs-docs-samples.git
cd nodejs-docs-samples/functions/scheduleinstance/
gcloud functions deploy startInstancePubSub \
   --trigger-topic start-instance-event \
   --runtime nodejs8

test functions error

gcloud functions call startInstancePubSub --data '{"data":"eyJ6b25lIjphc2lhLWVhc3QxLWMsImluc3RhbmNlIjoic2NhbGVvdXQtam9idm0ifQo="}'
error: |-
  Error: function execution failed. Details:
  Unexpected token a in JSON at position 8

**Comment by fhinkel** [comment]
@harryliu123 :wave: Thanks for reporting the issue!

@ace-n Could you please have a look at this? Seems like there's a problem with the `functions/scheduleinstance` sample. Thank you.

**Comment by ace-n** [comment]
Over to @djmailhot, who owns this sample (per CODEOWNERS) 🙂

**Comment by fhinkel** [comment]
Ping @djmailhot

**Comment by djmailhot** [comment]
@harryliu123, the data encoding string you used has a JSON formatting error.

yours:
encoded - eyJ6b25lIjphc2lhLWVhc3QxLWMsImluc3RhbmNlIjoic2NhbGVvdXQtam9idm0ifQo=
decoded - {"zone":asia-east1-c,"instance":"scaleout-jobvm"}

**corrected**:
decoded - {"zone":**"asia-east1-c"**,"instance":"scaleout-jobvm"}
encoded - **eyJ6b25lIjoiYXNpYS1lYXN0MS1jIiwiaW5zdGFuY2UiOiJzY2FsZW91dC1qb2J2bSJ9**

Additionally, this code sample has been updated to use [resource labels](https://cloud.google.com/compute/docs/labeling-resources) instead of instance names.  See the [instance scheduling tutorial](https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule) to learn how to use resource labels with this code sample.
