### ISSUE TITLE
Send notifications to Slack: How to acknowledge the alert is received so it is not repetitively posted on slack channel.

### ISSUE THREAD

**Issue by SaadBinShahid** [GoogleCloudPlatform/nodejs-docs-samples#1536]
Hi,

I am using; Programmatic Budgets Notification Examples "Send notifications to Slack
" @ https://cloud.google.com/billing/docs/how-to/notify#send_notifications_to_slack

```
const slack = require('slack');

// TODO(developer) replace these with your own values
const BOT_ACCESS_TOKEN =
  process.env.BOT_ACCESS_TOKEN || 'xxxx-111111111111-abcdefghidklmnopq';
const CHANNEL = process.env.SLACK_CHANNEL || 'general';

exports.notifySlack = async (pubsubEvent, context) => {
  const pubsubAttrs = pubsubEvent.attributes;
  const pubsubData = Buffer.from(pubsubEvent.data, 'base64').toString();
  const budgetNotificationText = `${pubsubAttrs}, ${pubsubData}`;

  await slack.chat.postMessage({
    token: BOT_ACCESS_TOKEN,
    channel: CHANNEL,
    text: budgetNotificationText,
  });

  return 'Slack notification sent successfully';
};
```

Every 20 minutes alert is posed on slack. How do I acknowledge the alert is received so it is not repetitively posted on slack channel?

Thanks!

**Comment by fhinkel** [comment]
👋 @SaadBinShahid Thanks for raising the issue. @ace-n , can you help out with this question about a `functions/billing` sample. Thanks

**Comment by ace-n** [comment]
Hi @SaadBinShahid,

Unfortunately there's [no way to limit](https://cloud.google.com/billing/docs/how-to/budgets#delivery_guarantees) these notifications within Cloud Billing itself.

Your best bet would be to store a `notified` flag somewhere outside the function (e.g. [Google Cloud Datastore](https://cloud.google.com/datastore/docs)), and have your function ignore any notifications once that flag is set.

(You could also store a timestamp - say, 24 hours from now - instead of a boolean flag and hide notifications until that timestamp has passed.)

Hope this helps!
