### ISSUE TITLE
I have issue to add the json key file 

### ISSUE THREAD

**Issue by muhammadsamir11** [GoogleCloudPlatform/nodejs-docs-samples#158]
Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.

can you help me how can i fix that

**Comment by jmdobry** [comment]
Can you please provide more information about your setup? Did you run `gcloud beta auth application-default login` or are you trying to use a service account? Is your `GOOGLE_APPLICATION_CREDENTIALS` environment variable set to the correct value?

**Comment by aligajani** [comment]
@jmdobry  Hey man, I am a bit confused. Do I have to use gcloud to use the natural language API, because it seems like an over kill. Can't I just supply the API key or the service account .json file and be ready to make calls from my PHP app using Guzzle. I haven't seen any API endpoint being accessed in such  a non-trivial way, such that it makes beginner trials boring and tedious

**Comment by jmdobry** [comment]
@aligajani You are not required to use Google client libraries in order to communicate with Google APIs, but it is useful if you don't have time to implement your own client library.

If you're struggling to deploy one of the Node.js samples in this repository, then opening an issue here is good way to get help, only you must provide enough information for me to be able to reproduce the error before I can help you, e.g. which sample you're trying to deploy, stack trace, app.yaml, package.json, Node version, etc.

If you're looking for free general support, you can hop onto our [Slack channels](https://gcp-slack.appspot.com/) and post your question (there's even a [php channel](https://googlecloud-community.slack.com/messages/php/)), or search [Stack Overflow](http://stackoverflow.com/). Here are some more [links to Google Cloud Platform developer communities](https://cloud.google.com/support/#developer-communities_1).

If you're looking for paid technical support, you can find that on [cloud.google.com/support](https://cloud.google.com/support/#technical-support).

**Comment by elibixby** [comment]
@aligajani Just to clarify what @jmdobry is saying:

You don't need `gcloud` to use Google APIs. In this case you can just point to a service account json file:

```
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/my/service_account.json
```

**Comment by aligajani** [comment]
@elibixby  Do you guys have a tutorial on how to use Natural Language API via PHP?

**Comment by jmdobry** [comment]
Not that I know of. When it appears it will appear here: https://github.com/GoogleCloudPlatform/php-docs-samples

**Comment by hung101** [comment]
i followed  instructions from [https://github.com/GoogleCloudPlatform/php-docs-samples](url) having the same issue, by just passing projectid, it prompt this Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by hung101** [comment]
I found the solution:

`putenv(GOOGLE_APPLICATION_CREDENTIALS=/[filekey].json);` 

must set the environment variable

**Comment by informaticosgb** [comment]
I solved it:

putenv('GOOGLE_APPLICATION_CREDENTIALS=../service-account.json');
$client = new Google_Client();
$client->useApplicationDefaultCredentials();
$client->setScopes(['https://www.googleapis.com/auth/analytics.readonly']);
$client->refreshTokenWithAssertion();
$token = $client->getAccessToken();
$accessToken = $token['access_token'];
dd($accessToken);

👍
