### ISSUE TITLE
functions/composer-storage-trigger/index.js sends nonexistent argument "iap.jwt" to "makeIapPostRequest"

### ISSUE THREAD

**Issue by starmandeluxe** [GoogleCloudPlatform/nodejs-docs-samples#1602]
It looks like the final argument in makeIapPostRequest ("jwt") was removed at some point (https://github.com/GoogleCloudPlatform/nodejs-docs-samples/commit/43cb78c469b1d7e3114b54fb81c9982ca50387f1#diff-03c121b657e9255e31ace2345598d678R152), but for some reason the code sample still provides it in the call to this function:

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/c00c94f6917b80be4b7484e8d0ee95e5cc5dd7e6/functions/composer-storage-trigger/index.js#L61

Why?

**Comment by fhinkel** [comment]
@ace-n , could you have a look at this `functions` sample? Thanks

**Comment by ace-n** [comment]
@leahecole owns this sample - over to you 🙂

**Comment by meredithslota** [comment]
I'm not sure if this makes sense but I'm adding the "composer" label so this is surfaced to our team, and dropping priority to P2.

**Comment by leahecole** [comment]
I'm investigating this now. I tried running the code in the [relevant tutorial](https://cloud.google.com/composer/docs/how-to/using/triggering-with-gcf#triggering-with-gcf-creating-a-function-nodejs) as is, and it seems to work - the DAG triggers and prints the appropriate info. 

I retried adding in the `jwt` parameter like it was before, and the DAG triggered then too, printing the appropriate info. This occurred because the `makeIapPostRequest` function never reads this value. The fact that the function never reads the value is likely why it was removed in this PR that was running eslint - it removed unused parameters. The line that you highlighted managed to get leftover somehow, but has since been updated. There are now no longer any references to this unused `jwt` - the ones that remain are used in the service account signature request. 

Thank you for opening this - I'm going to close it because as far as I can tell, the code doesn't need any updates at this time.
