### ISSUE TITLE
req.file is always undefined

### ISSUE THREAD

**Issue by jp3492** [GoogleCloudPlatform/nodejs-docs-samples#1937]
When using exactly the example provided by gcp, req.file is always undefined when sending a file as multipart/form-data.

here my html:
```
<form action="http://localhost:4000/upload" method="post" enctype="multipart/form-data">
      <input type="file" />
      <input type="submit" value="Submit" />
</form>
```

Im using the serverless-framework to run locally on port 4000.

the express is exactly the same as in the example provided.

**Comment by ace-n** [comment]
I suspect there are two possible fixes:
1. Your HTML is incorrect - you need `id` and `name` attributes, per [this example](https://www.w3schools.com/howto/howto_html_file_upload_button.asp).
2. I'm not sure we use `req.file`. See [this page](https://cloud.devsite.corp.google.com/functions/docs/writing/http#multipart_data) for an example of uploading files to a Cloud Function.

Since neither of these points to a bug in Cloud Functions itself, I'm going to close this issue. @jp3492 please reopen (and/or file an issue on the [Serverless.com GCF repo](https://github.com/serverless/serverless-google-cloudfunctions)) if neither of these solutions work.
