### ISSUE TITLE
functions: Avoid `require('googleapis')` for performance-sensitive samples

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#2125]
In the blog post [Tips for writing and deploying Node.js apps on Cloud Functions](https://cloud.google.com/blog/products/serverless/running-effective-nodejs-apps-on-cloud-functions), @bcoe suggests we can reduce a significant cold start overhead from hundreds of disk reads by making a change like:

```diff
-const {google} = require('googleapis');
+const google = require('googleapis/build/src/apis/sql');
const sql = google.sql('v1beta4');
```

When I run a [search for `require('googleapis')`](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/search?q=require%28%27googleapis%27%29) in this repository, I found 2 Cloud Functions samples using this approach:

* https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/49f8f6186611a7cd4f84fce14d94d687d2b8132c/functions/billing/test/index.test.js
* https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/49f8f6186611a7cd4f84fce14d94d687d2b8132c/functions/slack/index.js

In order to train developers to use the best practice approach in writing code, it would be great to apply this optimization unless doing so would overly-complicate the essential purpose of the sample.

Note: My understanding is this is also important for Cloud Run & App Engine Standard, but I do not see examples of `require('googleapis')` for those products in this repo.

**Comment by bcoe** [comment]
@grayside love it 😄 I'm also working on publishing these libraries individually, so that we could eventually have the more elegant:

```
const {google} = require('@googleapis/sql');
```

**Comment by fhinkel** [comment]
In case there's any confusion: 

If available, we want folks to use the dedicated client library, e.g., something like `const {sql} = require('@google-cloud/sql')` instead of the generated library`const google = require('googleapis/build/src/apis/sql')`.

Samples for using the generated library e.g.,`const google = require('googleapis/build/src/apis/sql')` should live here: https://github.com/googleapis/google-api-nodejs-client/tree/master/samples. This way the samples functions as a test for the generated libraries. If the sample is in this repo, it can only catch errors after a new version of the generated library is released. Of course, if the sample demonstrates GCF for GCF docs, `nodejs-docs-samples` is probably the better place for it.
