### ISSUE TITLE
Issue with importing the package into a react app

### ISSUE THREAD

**Issue by sevtekin** [GoogleCloudPlatform/nodejs-docs-samples#3629]
## In which file did you encounter the issue?
when you try to import @google-cloud/discoveryengine package in a react app webpack does not compile. same package on the same node environment/versions (v20.11.1) works in a nodejs app

## Did you change the file? If so, how?
no

## Describe the issue
here is the output when you try to start the react app. if you comment out the import statement 
import {DataStoreServiceClient} from '@google-cloud/discoveryengine'
everything works. Please see the attached error log
[error.log](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/files/14377049/error.log)

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by pattishin** [comment]
HI @sevtekin, thanks so much for submitting the issue. As this seems to be package specific problem rather than a samples one, please file this  against https://github.com/googleapis/google-cloud-node/tree/main/packages/google-cloud-discoveryengine if you are still experiencing issues that are specific to the library.
